version: '3'
services:
  notification-temp:
    build:
      context: .
      dockerfile: notification/Dockerfile
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - /opt/fruitnanny/nodejs/bin:/opt/fruitnanny/nodejs/bin
    depends_on:
      - nginx
      - janus
      - nodejs
    #command: /bin/bash
    #tty: true
    command: python3 /opt/fruitnanny/nodejs/bin/temperature.py

  notification-motion:
    image: fruitnanny_notification-temp
    restart: always
    network_mode: "host"
    privileged: true
    volumes:
      - /opt/fruitnanny/nodejs/bin:/opt/fruitnanny/nodejs/bin
    depends_on:
      - nginx
      - janus
      - nodejs
      - notification-temp
    #command: /bin/bash
    #tty: true
    command: python3 /opt/fruitnanny/nodejs/bin/motion.py
